"""Add cascade delete to event relationships

Revision ID: f17c00ffb35e
Revises: 0dfebdeb591a
Create Date: 2025-05-22 23:00:35.662362+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17c00ffb35e'
down_revision: Union[str, None] = '0dfebdeb591a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_changelog_event_id_fkey', 'event_changelog', type_='foreignkey')
    op.drop_constraint('event_changelog_created_by_fkey', 'event_changelog', type_='foreignkey')
    op.drop_constraint('event_changelog_version_id_fkey', 'event_changelog', type_='foreignkey')
    op.create_foreign_key(None, 'event_changelog', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_changelog', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_changelog', 'event_versions', ['version_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('event_permissions_event_id_fkey', 'event_permissions', type_='foreignkey')
    op.drop_constraint('event_permissions_user_id_fkey', 'event_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'event_permissions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('event_versions_created_by_fkey', 'event_versions', type_='foreignkey')
    op.drop_constraint('event_versions_event_id_fkey', 'event_versions', type_='foreignkey')
    op.create_foreign_key(None, 'event_versions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_versions', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint('events_owner_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_owner_id_fkey', 'events', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'event_versions', type_='foreignkey')
    op.drop_constraint(None, 'event_versions', type_='foreignkey')
    op.create_foreign_key('event_versions_event_id_fkey', 'event_versions', 'events', ['event_id'], ['id'])
    op.create_foreign_key('event_versions_created_by_fkey', 'event_versions', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'event_permissions', type_='foreignkey')
    op.drop_constraint(None, 'event_permissions', type_='foreignkey')
    op.create_foreign_key('event_permissions_user_id_fkey', 'event_permissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('event_permissions_event_id_fkey', 'event_permissions', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'event_changelog', type_='foreignkey')
    op.drop_constraint(None, 'event_changelog', type_='foreignkey')
    op.drop_constraint(None, 'event_changelog', type_='foreignkey')
    op.create_foreign_key('event_changelog_version_id_fkey', 'event_changelog', 'event_versions', ['version_id'], ['id'])
    op.create_foreign_key('event_changelog_created_by_fkey', 'event_changelog', 'users', ['created_by'], ['id'])
    op.create_foreign_key('event_changelog_event_id_fkey', 'event_changelog', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ### 